name: memory_tagz
version: 0.4.0
description: Demonstrates how to use the `memory_tagz` plugin.



environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bluetooth_serial: ^0.4.0
  cupertino_icons: ^1.0.3
  loading_animation_widget:
  flutter_icons: ^1.1.0
  flutter_svg: ^0.21.0+1
  flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0
  lottie: ^1.3.0
  image_picker: ^0.8.5
  tflite: ^1.1.2
  cloud_firestore: ^3.1.12
  neon: ^0.1.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^1.0.4

  
    
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
